### ISSUE TITLE
multiple color in one progress

### ISSUE THREAD

**Issue by kaushikpatel1396** [Yalantis/EatFit#10]
Similar to Google Fit Circular progress view, 
![screen shot 2016-08-26 at 3 19 09 pm](https://cloud.githubusercontent.com/assets/16894064/18001430/d114f5bc-6b37-11e6-9511-1954cc6a9196.png)

Like This.. Please Guide. @serejahh

**Comment by serejahh** [comment]
Hi @pareekkhushboo77

This task is quite complex. I'll leave the feature as low priority improvement but without time bounds

**Comment by rnkyr** [comment]
Hey, @pareekkhushboo77
We don't have any plans for supporting this project. We would gladly accept PRs if anyone willing to implement that enchantment
