### ISSUE TITLE
percentageLabel text does not appear and does not animate

### ISSUE THREAD

**Issue by SikandAlex** [Yalantis/EatFit#3]
I've included an example. I implemented all of the customization functions yet this is the final state of the view after all of the animations have completed. 

![screen shot 2016-07-12 at 1 10 34 pm](https://cloud.githubusercontent.com/assets/12959962/16765054/2101dac8-4832-11e6-8563-4bafcd2589f9.png)

**Comment by serejahh** [comment]
Hi @SikandAlex. Thanks for your interest to our component!
Could you provide more details? It'd be great if you provide your project

**Comment by SikandAlex** [comment]
It works now I must have been doing something wrong
