### ISSUE TITLE
App is crashing 

### ISSUE THREAD

**Issue by nentrast** [Yalantis/EatFit#4]
App crash when change view on pageView controller.

EatFit Demo Project[2416:92427] -[NSConcreteValue doubleValue]: unrecognized selector sent to instance 0x7f9808f17170
2016-07-13 22:31:08.496 EatFit Demo Project[2416:92427] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSConcreteValue doubleValue]: unrecognized selector sent to instance 0x7f9808f17170'

**Comment by houze2311** [comment]
Hello, nentrast.
Thank you for your interest to our component.
Is last changes from master?

**Comment by nentrast** [comment]
Yes its from master

**Comment by NSMyself** [comment]
@serejahh I don't think your PR fixes the issue because it doesn't only crash when rotating.

You just have to run the app, wait for the animation to finish in the very first page (when the water icon appears and the label says "Drink 500ml (...)" and swipe right.

Here's what I'm getting:

`2016-07-21 14:54:05.302 EatFit Demo Project[72558:11445117] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSConcreteValue doubleValue]: unrecognized selector sent to instance 0x7fbb49e27190'
*** First throw call stack:
(
    0   CoreFoundation                      0x000000010b1fcd85 __exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x000000010d8a9deb objc_exception_throw + 48
    2   CoreFoundation                      0x000000010b205d3d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
    3   CoreFoundation                      0x000000010b14bcfa ___forwarding___ + 970
    4   CoreFoundation                      0x000000010b14b8a8 _CF_forwarding_prep_0 + 120
    5   QuartzCore                          0x000000010c1f2d5c CAObject_setValueForKeyPath_ + 3495
    6   QuartzCore                          0x000000010c1db385 -[CALayer setValue:forKeyPath:] + 542
    7   QuartzCore                          0x000000010c1bffe2 -[CABasicAnimation applyForTime:presentationObject:modelObject:] + 959
    8   QuartzCore                          0x000000010c1ddd4c _ZN2CA5Layer18presentation_layerEPNS_11TransactionE + 408
    9   QuartzCore                          0x000000010c1e5f30 CALayerCreateImplicitAnimation + 124
    10  QuartzCore                          0x000000010c1e6128 -[CALayer(CALayerPrivate) implicitAnimationForKeyPath:] + 203
    11  QuartzCore                          0x000000010c1f60ae -[CAShapeLayer implicitAnimationForKeyPath:] + 50
    12  QuartzCore                          0x000000010c1fa97d +[CATransaction(CATransactionInternal) _implicitAnimationForLayer:keyPath:] + 79
    13  QuartzCore                          0x000000010c1df234 -[CALayer actionForKey:] + 463
    14  QuartzCore                          0x000000010c1da7fe _ZL12actionForKeyP7CALayerPN2CA11TransactionEP8NSString + 76
    15  QuartzCore                          0x000000010c1da78c _ZN2CA5Layer12begin_changeEPNS_11TransactionEjRP11objc_object + 140
    16  QuartzCore                          0x000000010c1dbe9d _ZN2CA5Layer12set_positionERKNS_4Vec2IdEEb + 235
    17  QuartzCore                          0x000000010c1dbfbd -[CALayer setPosition:] + 44
    18  QuartzCore                          0x000000010c1dc624 -[CALayer setFrame:] + 650
    19  EatFit Demo Project                 0x000000010afaf2a9 _TFC19EatFit_Demo_Project8DropView14layoutSubviewsfT_T_ + 569
    20  EatFit Demo Project                 0x000000010afaf5d2 _TToFC19EatFit_Demo_Project8DropView14layoutSubviewsfT_T_ + 34
    21  UIKit                               0x000000010c3e8980 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 703
    22  QuartzCore                          0x000000010c1e4c00 -[CALayer layoutSublayers] + 146
    23  QuartzCore                          0x000000010c1d908e _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 366
    24  QuartzCore                          0x000000010c1d8f0c _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
    25  QuartzCore                          0x000000010c1cd3c9 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 277
    26  QuartzCore                          0x000000010c1fb086 _ZN2CA11Transaction6commitEv + 486
    27  QuartzCore                          0x000000010c209b5c _ZN2CA7Display11DisplayLink14dispatch_itemsEyyy + 576
    28  CoreFoundation                      0x000000010b156074 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
    29  CoreFoundation                      0x000000010b155c21 __CFRunLoopDoTimer + 1089
    30  CoreFoundation                      0x000000010b117b11 __CFRunLoopRun + 1937
    31  CoreFoundation                      0x000000010b1170f8 CFRunLoopRunSpecific + 488
    32  GraphicsServices                    0x0000000110930ad2 GSEventRunModal + 161
    33  UIKit                               0x000000010c32df09 UIApplicationMain + 171
    34  EatFit Demo Project                 0x000000010afba112 main + 114
    35  libdyld.dylib                       0x000000010e36d92d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)`

**Comment by serejahh** [comment]
Should be solved in a new release soon
