### ISSUE TITLE
How to change background color of the whole view

### ISSUE THREAD

**Issue by SikandAlex** [Yalantis/EatFit#9]
I am able to change the color of the chart progress and the image through the provided chartColorForPage method but how can I change the background color of the view... I tried changing self.view.backgroundColor in my ViewController but it had no effect.

**Comment by serejahh** [comment]
Hi @SikandAlex

Unfortunately you can't customize it for now

**Comment by serejahh** [comment]
I've just added new data source method. By default it return white color as in the demo, but you can implement it and return your color

**Comment by SikandAlex** [comment]
Fantastic I'll try it out thank you Serhii

On Tue, Aug 23, 2016 at 1:39 AM, Serhii Butenko < notifications@github.com [notifications@github.com] > wrote:
I've just added new data source method. By default it return white color as in the demo, but you can implement it and return your color
